version: "3"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/config
      - downloads:/downloads #optional
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.entrypoints: "http"
      traefik.http.routers.sabnzbd.rule: "Host(`sabnzbd.internal.${DOMAIN}`)"
      traefik.http.middlewares.sabnzbd-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.sabnzbd.middlewares: "sabnzbd-https-redirect"
      traefik.http.routers.sabnzbd-secure.entrypoints: "https"
      traefik.http.routers.sabnzbd-secure.rule: "Host(`sabnzbd.internal.${DOMAIN}`)"
      traefik.http.routers.sabnzbd-secure.tls: true
      traefik.http.routers.sabnzbd-secure.service: "sabnzbd"
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
      traefik.docker.network: "proxy"
      com.centurylinklabs.watchtower.enable: true

networks:
  proxy:
    external: true

volumes:
  data:
  downloads: