http:
  routers:
    <service>:
      entryPoints:
        - "https"
      rule: "Host(`<service>.internal.<domain>`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: <service>

  services:
    <service>:
      loadBalancer:
        servers:
          - url: "<http|https>://<ip-address>:<port>"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
