version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - adguard_conf:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work
    labels:
      com.centurylinklabs.watchtower.enable: true

volumes:
  adguard_conf:
  adguard_work:
