version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports:
      # DNS
      - 53:53
      # # DHCP server
      # - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      # # HTTPS/DNS-over-HTTPS
      # - 443:443/tcp
      # # DNS-over-TLS
      # - 853:853/tcp
      # # DNS-over-QUIC
      # - 784:784/udp
      # # DNSCrypt
      # - 5443:5443/tcp
      # - 5443:5443/udp
      # # WebUI
      # - 3000:3000/tcp
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - adguard_conf:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work
    labels:
      caddy: ${URL:-adguard.example.com}
      caddy.reverse_proxy: "{{upstreams 3000}}"
      #caddy.tls: "internal"
      com.centurylinklabs.watchtower.enable: true

networks:
  proxy:
    external: true

volumes:
  adguard_conf:
  adguard_work:
